In [2]:
import pandas as pd
df = pd.read_csv('pokemon_data.csv')
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [9]:
#average of each one and check the stats on how they compare
#df.groupby(['Type 1']).mean().sort_values('Defense', ascending=False)
#df.groupby(['Type 1']).sum().sort_values('Defense', ascending=False)
df.groupby(['Type 1']).count()

,#,Name,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,,,
Bug,69,69,52,69,69,69,69,69,69,69,69
Dark,31,31,21,31,31,31,31,31,31,31,31
Dragon,32,32,21,32,32,32,32,32,32,32,32
Electric,44,44,17,44,44,44,44,44,44,44,44
Fairy,17,17,2,17,17,17,17,17,17,17,17
Fighting,27,27,7,27,27,27,27,27,27,27,27
Fire,52,52,24,52,52,52,52,52,52,52,52
Flying,4,4,2,4,4,4,4,4,4,4,4
Ghost,32,32,22,32,32,32,32,32,32,32,32
Grass,70,70,37,70,70,70,70,70,70,70,70
Ground,32,32,19,32,32,32,32,32,32,32,32
Ice,24,24,11,24,24,24,24,24,24,24,24
Normal,98,98,37,98,98,98,98,98,98,98,98
Poison,28,28,13,28,28,28,28,28,28,28,28
Psychic,57,57,19,57,57,57,57,57,57,57,57
Rock,44,44,35,44,44,44,44,44,44,44,44
Steel,27,27,22,27,27,27,27,27,27,27,27
Water,112,112,53,112,112,112,112,112,112,112,112

In [11]:
df['count'] = 1

df.groupby(['Type 1']).count()['count']

Type 1
Bug          69
Dark         31
Dragon       32
Electric     44
Fairy        17
Fighting     27
Fire         52
Flying        4
Ghost        32
Grass        70
Ground       32
Ice          24
Normal       98
Poison       28
Psychic      57
Rock         44
Steel        27
Water       112
Name: count, dtype: int64